"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-29
"""

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("record_type", sa.String(length=32), nullable=False),
        sa.Column("record_id", sa.String(length=32), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("field", sa.String(length=64), nullable=True),
        sa.Column("old_value", sa.JSON(), nullable=True),
        sa.Column("new_value", sa.JSON(), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("history", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_history_record_id"), ["record_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_history_timestamp"), ["timestamp"], unique=False)

    op.create_table(
        "investigation_info",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "nodes",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("charge", sa.Integer(), nullable=True),
        sa.Column("multiplicity", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("geometry", sa.JSON(), nullable=True),
        sa.Column("derived_from_id", sa.String(length=32), nullable=True),
        sa.Column("pos_x", sa.Double(), nullable=False),
        sa.Column("pos_y", sa.Double(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["derived_from_id"], ["nodes.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("nodes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_nodes_seq"), ["seq"], unique=False)

    op.create_table(
        "calculations",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("node_id", sa.String(length=32), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("program", sa.String(length=32), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("calculations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_calculations_node_id"), ["node_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("calculations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_calculations_node_id"))

    op.drop_table("calculations")
    with op.batch_alter_table("nodes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_nodes_seq"))

    op.drop_table("nodes")
    op.drop_table("investigation_info")
    with op.batch_alter_table("history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_history_timestamp"))
        batch_op.drop_index(batch_op.f("ix_history_record_id"))

    op.drop_table("history")
    # ### end Alembic commands ###
