"""gaussian import

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-29

Phase 2: levels of theory, named custom basis sets and dispersions (FR-CALC-03, D59), copied
source files (FR-FILE-01) and calculation results. Existing calculations get empty values.
"""

import sqlalchemy as sa
from alembic import op

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "custom_bases",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("definition", sa.JSON(), nullable=False),
        sa.Column("fingerprints", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "custom_dispersions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("base", sa.String(length=64), nullable=False),
        sa.Column("iops", sa.JSON(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "levels_of_theory",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("program", sa.String(length=32), nullable=False),
        sa.Column("method", sa.String(length=64), nullable=False),
        sa.Column("basis", sa.String(length=64), nullable=False),
        sa.Column("dispersion", sa.String(length=64), nullable=False),
        sa.Column("solvation_model", sa.String(length=32), nullable=False),
        sa.Column("solvent", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "program", "method", "basis", "dispersion", "solvation_model", "solvent"
        ),
    )
    op.create_table(
        "source_files",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("stored_path", sa.String(length=512), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("origin_device", sa.String(length=200), nullable=False),
        sa.Column("origin_path", sa.Text(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("imported_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("source_files", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_source_files_checksum"), ["checksum"], unique=False)

    op.create_table(
        "calculation_results",
        sa.Column("calculation_id", sa.String(length=32), nullable=False),
        sa.Column("energy", sa.Double(), nullable=True),
        sa.Column("zpe", sa.Double(), nullable=True),
        sa.Column("e_corr", sa.Double(), nullable=True),
        sa.Column("h_corr", sa.Double(), nullable=True),
        sa.Column("g_corr", sa.Double(), nullable=True),
        sa.Column("e_zpe", sa.Double(), nullable=True),
        sa.Column("e_thermal", sa.Double(), nullable=True),
        sa.Column("h", sa.Double(), nullable=True),
        sa.Column("g", sa.Double(), nullable=True),
        sa.Column("temperature", sa.Double(), nullable=True),
        sa.Column("pressure", sa.Double(), nullable=True),
        sa.Column("molecular_mass", sa.Double(), nullable=True),
        sa.Column("symmetry_number", sa.Integer(), nullable=True),
        sa.Column("point_group", sa.String(length=16), nullable=True),
        sa.Column("rotational_constants", sa.JSON(), nullable=True),
        sa.Column("rotational_temperatures", sa.JSON(), nullable=True),
        sa.Column("frequencies", sa.JSON(), nullable=False),
        sa.Column("reduced_masses", sa.JSON(), nullable=False),
        sa.Column("normal_modes", sa.JSON(), nullable=False),
        sa.Column("imaginary_count", sa.Integer(), nullable=True),
        sa.Column("optimization_converged", sa.Boolean(), nullable=True),
        sa.Column("geometry_count", sa.Integer(), nullable=False),
        sa.Column("printed", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["calculation_id"], ["calculations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("calculation_id"),
    )
    with op.batch_alter_table("calculations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "program_version",
                sa.String(length=32),
                nullable=False,
                server_default=sa.text("''"),
            )
        )
        batch_op.add_column(sa.Column("level_id", sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column("geometry_level_id", sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column("parsed_level", sa.JSON(), nullable=True))
        batch_op.add_column(
            sa.Column("route", sa.Text(), nullable=False, server_default=sa.text("''"))
        )
        batch_op.add_column(
            sa.Column("title", sa.Text(), nullable=False, server_default=sa.text("''"))
        )
        batch_op.add_column(sa.Column("step_index", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("step_count", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "termination",
                sa.String(length=16),
                nullable=False,
                server_default=sa.text("'unknown'"),
            )
        )
        batch_op.add_column(sa.Column("charge", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("multiplicity", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("geometry", sa.JSON(), nullable=True))
        batch_op.add_column(
            sa.Column("parse_warnings", sa.JSON(), nullable=False, server_default=sa.text("'[]'"))
        )
        batch_op.add_column(sa.Column("source_file_id", sa.String(length=32), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_calculations_source_file_id"), ["source_file_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_calculations_geometry_level_id",
            "levels_of_theory",
            ["geometry_level_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            "fk_calculations_level_id",
            "levels_of_theory",
            ["level_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            "fk_calculations_source_file_id",
            "source_files",
            ["source_file_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("calculations", schema=None) as batch_op:
        batch_op.drop_constraint("fk_calculations_source_file_id", type_="foreignkey")
        batch_op.drop_constraint("fk_calculations_level_id", type_="foreignkey")
        batch_op.drop_constraint("fk_calculations_geometry_level_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_calculations_source_file_id"))
        batch_op.drop_column("source_file_id")
        batch_op.drop_column("parse_warnings")
        batch_op.drop_column("geometry")
        batch_op.drop_column("multiplicity")
        batch_op.drop_column("charge")
        batch_op.drop_column("termination")
        batch_op.drop_column("step_count")
        batch_op.drop_column("step_index")
        batch_op.drop_column("title")
        batch_op.drop_column("route")
        batch_op.drop_column("parsed_level")
        batch_op.drop_column("geometry_level_id")
        batch_op.drop_column("level_id")
        batch_op.drop_column("program_version")

    op.drop_table("calculation_results")
    with op.batch_alter_table("source_files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_files_checksum"))

    op.drop_table("source_files")
    op.drop_table("levels_of_theory")
    op.drop_table("custom_dispersions")
    op.drop_table("custom_bases")
    # ### end Alembic commands ###
