"""pathway structure

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-29

Phase 3: reaction steps (FR-STEP), branches with parents (FR-BR), group nodes (FR-GRP) and
transitions (FR-EDGE). Existing nodes get no step, branch or group.
"""

import sqlalchemy as sa
from alembic import op

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reaction_steps",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "branches",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("colour", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("split_node_id", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["split_node_id"], ["nodes.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "group_nodes",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("step_id", sa.String(length=32), nullable=True),
        sa.Column("representative_id", sa.String(length=32), nullable=True),
        sa.Column("outgoing_branch_id", sa.String(length=32), nullable=True),
        sa.Column("pos_x", sa.Double(), nullable=False),
        sa.Column("pos_y", sa.Double(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["outgoing_branch_id"], ["branches.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["representative_id"], ["nodes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["step_id"], ["reaction_steps.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "branch_parents",
        sa.Column("branch_id", sa.String(length=32), nullable=False),
        sa.Column("parent_id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_id"], ["branches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("branch_id", "parent_id"),
    )
    op.create_table(
        "group_incoming_branches",
        sa.Column("group_id", sa.String(length=32), nullable=False),
        sa.Column("branch_id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["group_id"], ["group_nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("group_id", "branch_id"),
    )
    op.create_table(
        "transitions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("source_node_id", sa.String(length=32), nullable=True),
        sa.Column("source_group_id", sa.String(length=32), nullable=True),
        sa.Column("target_node_id", sa.String(length=32), nullable=True),
        sa.Column("target_group_id", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "(source_node_id IS NULL) != (source_group_id IS NULL)", name="one_source"
        ),
        sa.CheckConstraint(
            "(target_node_id IS NULL) != (target_group_id IS NULL)", name="one_target"
        ),
        sa.ForeignKeyConstraint(["source_group_id"], ["group_nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_group_id"], ["group_nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("transitions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_transitions_source_group_id"), ["source_group_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_transitions_source_node_id"), ["source_node_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_transitions_target_group_id"), ["target_group_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_transitions_target_node_id"), ["target_node_id"], unique=False
        )

    with op.batch_alter_table("nodes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("step_id", sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column("branch_id", sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column("group_id", sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column("origin_branch_id", sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f("ix_nodes_branch_id"), ["branch_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_nodes_group_id"), ["group_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_nodes_step_id"), ["step_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_nodes_branch_id", "branches", ["branch_id"], ["id"], ondelete="SET NULL"
        )
        batch_op.create_foreign_key(
            "fk_nodes_step_id", "reaction_steps", ["step_id"], ["id"], ondelete="SET NULL"
        )
        batch_op.create_foreign_key(
            "fk_nodes_group_id", "group_nodes", ["group_id"], ["id"], ondelete="SET NULL"
        )
        batch_op.create_foreign_key(
            "fk_nodes_origin_branch_id",
            "branches",
            ["origin_branch_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    with op.batch_alter_table("nodes", schema=None) as batch_op:
        batch_op.drop_constraint("fk_nodes_origin_branch_id", type_="foreignkey")
        batch_op.drop_constraint("fk_nodes_group_id", type_="foreignkey")
        batch_op.drop_constraint("fk_nodes_step_id", type_="foreignkey")
        batch_op.drop_constraint("fk_nodes_branch_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_nodes_step_id"))
        batch_op.drop_index(batch_op.f("ix_nodes_group_id"))
        batch_op.drop_index(batch_op.f("ix_nodes_branch_id"))
        batch_op.drop_column("origin_branch_id")
        batch_op.drop_column("group_id")
        batch_op.drop_column("branch_id")
        batch_op.drop_column("step_id")

    op.drop_table("transitions")
    op.drop_table("group_incoming_branches")
    op.drop_table("branch_parents")
    op.drop_table("group_nodes")
    op.drop_table("branches")
    op.drop_table("reaction_steps")
